services:
  nginx:
    image: nginx:1.19.6-alpine
    command: ["nginx", "-g", "daemon off;", "-c", "/nginx/conf/nginx.conf"]
    restart: always
    volumes:
      - ./nginx/nginx.conf:/nginx/conf/nginx.conf:ro
      - ./nginx/mime.types:/nginx/conf/mime.types:ro
      - ./nginx/data:/nginx/data:ro
    ports:
      - "8808:80"
    network_mode: "bridge"
    links:
      - bitnuke
  redis:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - ./redis/:/data/:rw
    expose:
      - "6397"
    command: redis-server --save 20 1
    network_mode: "bridge"
  bitnuke:
    image: unixvoid/bitnuke
    restart: always
    depends_on:
      - redis
    volumes:
      - ../config.gcfg:/config.gcfg:ro
      - ../data/:/tmp/bitnuke_data/:rw
    expose:
      - "8808"
    network_mode: "bridge"
    links:
      - redis
